name: Run Robot Framework Tests on LambdaTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-appiumlibrary

      - name: Run Robot Framework Tests
        env:
          LT_USERNAME: ${LT_USERNAME}
          LT_ACCESS_KEY: ${LT_ACCESS_KEY}
        run: |
          robot --variable LT_USERNAME:fabricio.santos --variable LT_ACCESS_KEY:qKjyRUVdbDo01XDl3qdK7hdbWHbCFTQNdknvqvbvHhjDLA8Dod --variable version:15 --variable devicelog:True --variable CURDIR:${{ github.workspace }} tests/Picpay.robot