name: Run Robot Framework Tests on LambdaTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          - name: Run Robot Framework Tests
          env:
            LT_USERNAME: ${{ secrets.LT_USERNAME }}
            LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          run: |
            robot --variable REMOTE_URL:"http://${{ secrets.LT_USERNAME }}:${{ secrets.LT_ACCESS_KEY }}@hub.lambdatest.com/wd/hub" --variable CAPABILITIES:${{ github.workspace }}/capabilities.json